sudo: false
language: erlang
otp_release:
  - 19.3
  - 20.0
services:
  - redis-server
before_install:
  - rvm use 2.4.2 --install --binary --fuzzy
  - gem install anycablebility
  - wget https://s3.amazonaws.com/rebar3/rebar3 
  - chmod +x rebar3
script:
  - "./rebar3 eunit"
  - "./rebar3 ct"
  - "anycablebility -c "rebar3 shell" --target-url="ws://localhost:8081/ws/cable" --wait-command=5"
